--- 
javascripts: 
- base:
  - google_analytics
  - application
  - countdown
- points:
  - jquery.templates
  - jquery.serializeobject
  - jquery.ajaxretry
  - jquery.sprintf
  - jquery.ceebox
  - points

stylesheets: 
- base: 
  - screen
  - application
  - handheld
- ie:
  - ie
