login: &login
  adapter: mysql
  database: rw24
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *login

test:
  <<: *login
  database: rw24_test

cucumber:
  <<: *login
  database: rw24_test

staging:
  <<: *login

production:
  <<: *login
