login: &login
  adapter: mysql2
  database: rw24
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *login

test:
  <<: *login
  database: rw24_test<%= ENV["TEST_ENV_NUMBER"] %>

staging:
  <<: *login

production:
  <<: *login
