login: &login
  adapter: mysql
  database: rw24
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *login

staging:
  <<: *login

production:
  <<: *login
  database: riverwe_rw24
  username: riverwe_rw24
  password: ***REMOVED***
  socket: /var/lib/mysql/mysql.sock
