development: &login
  adapter: mysql
  database: rw24
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  database: rw24_test
  <<: *login

cucumber:
  database: rw24_test
  <<: *login
